;;; jacob-consult-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "jacob-consult" "jacob-consult.el" "f0bd7dd58f4e9e121c547b186156f494")
;;; Generated autoloads from jacob-consult.el

(autoload 'jacob-consult-buffer-state-no-tramp "jacob-consult" "\
Buffer state function that doesn't preview Tramp buffers.")

(autoload 'jacob-project-search "jacob-consult" "\
Wrapper for grep commands." t)

;;;***

;;; End of scraped data

(provide 'jacob-consult-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jacob-consult-autoloads.el ends here
