;;; jacob-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;;; Code:



;;; Generated autoloads from jacob-ace-window.el

(register-definition-prefixes "jacob-ace-window" '("jacob-split-or-switch-window"))


;;; Generated autoloads from jacob-apheleia.el

(register-definition-prefixes "jacob-apheleia" '("jacob-"))


;;; Generated autoloads from jacob-autoinsert.el

(register-definition-prefixes "jacob-autoinsert" '("jacob-define-auto-insert"))


;;; Generated autoloads from jacob-avy.el

(register-definition-prefixes "jacob-avy" '("jacob-avy-"))


;;; Generated autoloads from jacob-bookmark.el

(register-definition-prefixes "jacob-bookmark" '("jacob-bookmark-"))


;;; Generated autoloads from jacob-cecli.el

(register-definition-prefixes "jacob-cecli" '("jacob-cecli"))


;;; Generated autoloads from jacob-compile.el

(register-definition-prefixes "jacob-compile" '("jacob-compilation-project-file"))


;;; Generated autoloads from jacob-consult.el

(autoload 'jacob-consult-buffer-state-no-tramp "jacob-consult" "\
Buffer state function that doesn't preview Tramp buffers.")


;;; Generated autoloads from jacob-consult-symbol.el

(register-definition-prefixes "jacob-consult-symbol" '("jacob-consult-symbol--default-action"))


;;; Generated autoloads from jacob-csharp-mode.el

(register-definition-prefixes "jacob-csharp-mode" '("csharp-toolbox-" "jacob-"))


;;; Generated autoloads from jacob-editing-commands.el

(register-definition-prefixes "jacob-editing-commands" '("jacob-" "xah-"))


;;; Generated autoloads from jacob-eglot.el

(register-definition-prefixes "jacob-eglot" '("jacob-"))


;;; Generated autoloads from jacob-eshell.el

(register-definition-prefixes "jacob-eshell" '("jacob-eshell-windows-confirm-terminate-batch-job"))


;;; Generated autoloads from jacob-format-words.el

(autoload 'jacob-format-words "jacob-format-words" "\
Command for formating words into identifiers when writing code.

On first use, ask for formatting style (e.g. kebab, camel,
etc).  Format one word backwards in selected style and store the style
and the position of point after formatting, return point to where it
was when command called.

On consecutive use, apply stored formatting to word before stored
point." t)
(register-definition-prefixes "jacob-format-words" '("jacob-format-words-style-and-start"))


;;; Generated autoloads from jacob-gitlab.el

(register-definition-prefixes "jacob-gitlab" '("jacob-gitlab-push-set-upstream"))


;;; Generated autoloads from jacob-help-fns.el

(register-definition-prefixes "jacob-help-fns" '("jacob-help-edit"))


;;; Generated autoloads from jacob-init-helpers.el

(register-definition-prefixes "jacob-init-helpers" '("jacob-defhookf"))


;;; Generated autoloads from jacob-long-time.el

(autoload 'jacob-display-time "jacob-long-time" "\
Display the current date and time in the echo area." t)
(register-definition-prefixes "jacob-long-time" '("jacob-"))


;;; Generated autoloads from jacob-modal-editing.el

(register-definition-prefixes "jacob-modal-editing" '("jacob-modal-editing-"))


;;; Generated autoloads from jacob-modal-editing-config.el

(register-definition-prefixes "jacob-modal-editing-config" '("jacob-modal-editing-"))


;;; Generated autoloads from jacob-org.el

(register-definition-prefixes "jacob-org" '("jacob-org-"))


;;; Generated autoloads from jacob-package.el

(register-definition-prefixes "jacob-package" '("jacob-package-upgrade"))


;;; Generated autoloads from jacob-project.el

(autoload 'jacob-dired-in-other-project "jacob-project" "\
Switch to another project and open `dired' there." t)


;;; Generated autoloads from jacob-pulse.el

(register-definition-prefixes "jacob-pulse" '("jacob-pulse-"))


;;; Generated autoloads from jacob-puni.el

(register-definition-prefixes "jacob-puni" '("jacob-puni-copy-line"))


;;; Generated autoloads from jacob-rofi.el

(autoload 'jacob-rofi "jacob-rofi" "\
Rofi like thing.

Should work on linux and mac. On Linux, wmctrl is used.

1. Create a list of actions from various action sources (e.g. launch
an application, raise an open application, power off the system).
2. Use `completing-read' to select an action.
3. Carry out the selected action." t)
(register-definition-prefixes "jacob-rofi" '("jacob-"))


;;; Generated autoloads from jacob-ryo-modal.el

(register-definition-prefixes "jacob-ryo-modal" '("global-ryo-modal-mode" "jacob-ryo-modal-fix-cursor"))


;;; Generated autoloads from jacob-scala.el

(register-definition-prefixes "jacob-scala" '("jacob-"))


;;; Generated autoloads from jacob-shadow-theme.el

(register-definition-prefixes "jacob-shadow-theme" '("jacob-shadow"))


;;; Generated autoloads from jacob-sql.el

(register-definition-prefixes "jacob-sql" '("jacob-sql"))


;;; Generated autoloads from jacob-thingatpt.el

(register-definition-prefixes "jacob-thingatpt" '("jacob-bounds-of-"))


;;; Generated autoloads from jacob-trim-quotes.el

(autoload 'jacob-trim-quotes-mode "jacob-trim-quotes" "\
Minor mode to prevent the yanking of strings from messing up existing strings at point.

This is a minor mode.  If called interactively, toggle the
`Jacob-Trim-Quotes mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `jacob-trim-quotes-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "jacob-trim-quotes" '("jacob-trim-quotes--"))


;;; Generated autoloads from jacob-yasnippet.el

(register-definition-prefixes "jacob-yasnippet" '("jacob-"))


;;; Generated autoloads from sln-mode.el

(autoload 'sln-mode "sln-mode" "\
Major mode for editing msvc's *.sln files.
Turning on sln mode runs the normal hook `sln-mode-hook'.

(fn)" t)
(register-definition-prefixes "sln-mode" '("sln-"))

;;; End of scraped data

(provide 'jacob-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jacob-autoloads.el ends here
