;;; jacob-bookmark-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "jacob-bookmark" "jacob-bookmark.el" "d33087c3bfcba8e907188d075a4f99c8")
;;; Generated autoloads from jacob-bookmark.el

(autoload 'jacob-bookmark-command "jacob-bookmark" "\
Launch the command stored in BOOKMARK.

Intended for running applications.

\(fn BOOKMARK)")

(autoload 'jacob-bookmark-firefox "jacob-bookmark" "\
Open BOOKMARK in firefox.

\(fn BOOKMARK)")

(autoload 'jacob-bookmark-chrome "jacob-bookmark" "\
Open BOOKMARK in chrome.

\(fn BOOKMARK)")

;;;***

;;; End of scraped data

(provide 'jacob-bookmark-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jacob-bookmark-autoloads.el ends here
