;;; jacob-scala-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "jacob-scala" "jacob-scala.el" "d00200457e9b6d5de56422063206a839")
;;; Generated autoloads from jacob-scala.el

(autoload 'jacob-scala-indentation-to-block "jacob-scala" "\
Convert the indentation based syntax at point to block based syntax." t)

(autoload 'jacob-scala-test-file "jacob-scala" "\
Test the current file." t)

(autoload 'jacob-scala-dollar "jacob-scala" "\
Insert a dollar. If inside a string, enable string interpolation." t)

(autoload 'jacob-scala-package "jacob-scala" "\
Return the package of the current scala file.")

;;;### (autoloads "actual autoloads are elsewhere" "jacob-scala"
;;;;;;  "jacob-scala.el" (27040 39479 843913 655000))
;;; Generated autoloads from jacob-scala.el

(register-definition-prefixes "jacob-scala" '("jacob-scala--"))

;;;***

;;;***

;;; End of scraped data

(provide 'jacob-scala-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jacob-scala-autoloads.el ends here
