;;; jacob-trim-quotes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "jacob-trim-quotes" "jacob-trim-quotes.el"
;;;;;;  "03ad039271cbb7831b57e83c6c0fc11a")
;;; Generated autoloads from jacob-trim-quotes.el

(autoload 'jacob-trim-quotes-mode "jacob-trim-quotes" "\
Minor mode to prevent the yanking of strings from messing up existing strings at point.

This is a minor mode.  If called interactively, toggle the
`Jacob-Trim-Quotes mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `jacob-trim-quotes-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

\(fn &optional ARG)" t)

;;;### (autoloads "actual autoloads are elsewhere" "jacob-trim-quotes"
;;;;;;  "jacob-trim-quotes.el" (27034 12231 96013 438000))
;;; Generated autoloads from jacob-trim-quotes.el

(register-definition-prefixes "jacob-trim-quotes" '("jacob-trim-quotes--"))

;;;***

;;;***

;;; End of scraped data

(provide 'jacob-trim-quotes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jacob-trim-quotes-autoloads.el ends here
