;;; xah-fly-keys-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xah-fly-keys.el

(defvar xah-fly-keys nil "\
Non-nil if Xah-Fly-Keys mode is enabled.
See the `xah-fly-keys' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `xah-fly-keys'.")
(custom-autoload 'xah-fly-keys "xah-fly-keys" nil)
(autoload 'xah-fly-keys "xah-fly-keys" "\
A modal keybinding set, like vim, but based on ergonomic

  principles, like Dvorak layout.

URL `http://xahlee.info/emacs/misc/xah-fly-keys.html'

This is a global minor mode.  If called interactively, toggle the
`Xah-Fly-Keys mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='xah-fly-keys)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "xah-fly-keys" '("xah-"))

;;; End of scraped data

(provide 'xah-fly-keys-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xah-fly-keys-autoloads.el ends here
